const $ = s => document.querySelector(s), starter = ["assets/starter/manas-1.jpg", "assets/starter/manas-2.jpg"];
const toggle = $("#toggle"), input = $("#photos"), deck = $("#deck"), note = $("#note"), status = $("#status");
let state = { mememytabEnabled: false, mememytabPhotos: [] };
function render() { const cards = state.mememytabPhotos.length ? state.mememytabPhotos : starter; toggle.textContent = state.mememytabEnabled ? "Turn off" : "Turn on"; toggle.classList.toggle("off", state.mememytabEnabled); note.textContent = state.mememytabPhotos.length ? `${state.mememytabPhotos.length} custom photos ready.` : "2 starter photos ready."; deck.innerHTML = cards.map((src, i) => `<button class="thumb" ${state.mememytabPhotos.length ? `data-x="${i}"` : "disabled"}><img src="${src}">${state.mememytabPhotos.length ? "×" : ""}</button>`).join(""); document.querySelectorAll("[data-x]").forEach(b => b.onclick = async () => { state.mememytabPhotos.splice(+b.dataset.x, 1); await save(); }); }
async function tell() { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id) return; try { await chrome.tabs.sendMessage(tab.id, { type: "MEME_MY_TAB", enabled: state.mememytabEnabled, photos: state.mememytabPhotos }); } catch { status.textContent = "Open a normal website, then try again."; } }
async function save() { await chrome.storage.local.set(state); render(); await tell(); }
function read(file) { return new Promise((resolve, reject) => { if (file.size > 3 * 1024 * 1024) return reject(`${file.name} is over 3 MB.`); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(`Could not read ${file.name}.`); reader.readAsDataURL(file); }); }
chrome.storage.local.get(state, saved => { state = saved; render(); });
toggle.onclick = async () => { state.mememytabEnabled = !state.mememytabEnabled; await save(); };
input.onchange = async () => { const files = [...input.files].slice(0, 5 - state.mememytabPhotos.length); try { state.mememytabPhotos.push(...await Promise.all(files.map(read))); await save(); status.textContent = "Deck loaded. Let it loose."; } catch (e) { status.textContent = e; } input.value = ""; };
